package HCMUTE.SocialMedia.Enums;

public enum TypeSearchEnum {
    YOUR_FRIEND,
    FRIEND_REQUEST,
    MAKE_FRIEND,
    MAKED_FRIEND,
    JOINED_GROUP,
    JOIN_GROUP_PRIVATE,
    JOIN_GROUP_PUBLIC,
    UNJOIN_GROUP_PRIVATE,
    UNJOIN_GROUP_PUBLIC,
}
